import os
import sys
import json
import base64
from pathlib import Path
from typing import Optional, cast
from anthropic import Anthropic
from anthropic.types.base64_image_source_param import Base64ImageSourceParam
from anthropic.types.image_block_param import ImageBlockParam
from anthropic.types.text_block_param import TextBlockParam
from anthropic.types.text_block import TextBlock
from anthropic.types.thinking_block import ThinkingBlock
from dotenv import load_dotenv

ROOT_DIR = Path(__file__).resolve().parents[2]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from src.execution.telemetry import log_guardian_audit

load_dotenv()

client = Anthropic()

GUARDIAN_SYSTEM_PROMPT = """You are Aether-Flow's Multimodal Guardian — a quality assurance agent that audits pipeline outputs before deployment.

You receive charts and visualizations generated by the pipeline. Your job is to:
1. Visually inspect the chart for quality, correctness, and completeness
2. Identify any anomalies, data issues, or visual problems
3. Make a pass/fail deployment decision
4. Provide specific, actionable feedback

Audit criteria:
- Data integrity: Does the chart show real, meaningful data (not zeros, nulls, or nonsense values)?
- Visual quality: Are axes labeled? Is the title present? Are values readable?
- Business logic: Do the numbers make sense for the domain?
- Completeness: Does the output fulfill what was requested?

Respond ONLY with valid JSON:
{
  "verdict": "PASS" or "FAIL",
  "confidence": 0.0-1.0,
  "findings": {
    "data_integrity": "observation about the data shown",
    "visual_quality": "observation about chart quality",
    "business_logic": "observation about whether values make sense",
    "completeness": "observation about whether the task was fulfilled"
  },
  "issues": ["list of specific problems found, empty if none"],
  "recommendation": "one sentence deployment recommendation",
  "metrics_extracted": {
    "key": "value pairs of important numbers visible in the chart"
  }
}"""


def load_image_as_base64(filepath: str) -> tuple[str, str]:
    """Load an image file and return base64 encoded string with media type."""
    path = Path(filepath)

    ext = path.suffix.lower()
    media_type_map = {
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".gif": "image/gif",
        ".webp": "image/webp"
    }
    media_type = media_type_map.get(ext, "image/png")

    with open(filepath, "rb") as f:
        image_data = base64.standard_b64encode(f.read()).decode("utf-8")

    return image_data, media_type


def audit_chart(
    filepath: str,
    step_context: str,
    pipeline_goal: str,
    run_uuid: Optional[str] = None
) -> dict:
    """
    Send a chart to Claude Vision for quality audit.
    Logs result to telemetry if run_uuid provided.
    """
    print(f"\n👁️  Guardian auditing: {filepath}")

    if not os.path.exists(filepath):
        audit = {
            "verdict": "FAIL",
            "confidence": 1.0,
            "findings": {},
            "issues": [f"File not found: {filepath}"],
            "recommendation": "Pipeline output is missing — do not deploy.",
            "metrics_extracted": {}
        }
        if run_uuid:
            log_guardian_audit(
                run_uuid=run_uuid,
                chart_filepath=filepath,
                verdict="FAIL",
                confidence=1.0,
                findings={},
                issues=[f"File not found: {filepath}"],
                deploy_approved=False
            )
        return audit

    image_data, media_type = load_image_as_base64(filepath)

    prompt = f"""Audit this pipeline output chart.

Pipeline goal: {pipeline_goal}
Step that generated this: {step_context}
File: {filepath}

Inspect the chart carefully and provide your audit verdict."""

    image_source = cast(Base64ImageSourceParam, {
        "type": "base64",
        "media_type": media_type,
        "data": image_data,
    })
    image_block: ImageBlockParam = {
        "type": "image",
        "source": image_source,
    }
    text_block: TextBlockParam = {
        "type": "text",
        "text": prompt,
    }

    response = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=1500,
        system=GUARDIAN_SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": [image_block, text_block]
            }
        ]
    )

    first_block = response.content[0]
    if first_block.type == "text":
        raw = cast(TextBlock, first_block).text.strip()
    elif first_block.type == "thinking":
        raw = cast(ThinkingBlock, first_block).thinking.strip()
    else:
        raw = ""
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()

    try:
        audit = json.loads(raw)
        verdict = audit.get("verdict", "FAIL")
        confidence = audit.get("confidence", 0.0)
        icon = "✅" if verdict == "PASS" else "❌"
        print(f"     {icon} Verdict: {verdict} (confidence: {confidence:.0%})")
        print(f"     → {audit.get('recommendation', '')}")

        # Log to telemetry
        if run_uuid:
            log_guardian_audit(
                run_uuid=run_uuid,
                chart_filepath=filepath,
                verdict=verdict,
                confidence=confidence,
                findings=audit.get("findings", {}),
                issues=audit.get("issues", []),
                deploy_approved=(verdict == "PASS")
            )

        return audit

    except json.JSONDecodeError as e:
        print(f"     ✗ Failed to parse audit: {e}")
        audit = {
            "verdict": "FAIL",
            "confidence": 0.5,
            "findings": {},
            "issues": [f"Audit parsing failed: {str(e)}"],
            "recommendation": "Manual review required.",
            "metrics_extracted": {},
            "raw": raw
        }
        if run_uuid:
            log_guardian_audit(
                run_uuid=run_uuid,
                chart_filepath=filepath,
                verdict="FAIL",
                confidence=0.5,
                findings={},
                issues=[f"Audit parsing failed: {str(e)}"],
                deploy_approved=False
            )
        return audit


def audit_pipeline_outputs(
    results: dict,
    plan: dict,
    pipeline_goal: str,
    run_uuid: Optional[str] = None
) -> dict:
    """
    Scan all pipeline results for chart outputs and audit each one.
    Returns a guardian report with overall deployment decision.
    """
    print(f"\n🛡️  Multimodal Guardian — auditing pipeline outputs...")

    audits = {}
    chart_extensions = {".png", ".jpg", ".jpeg", ".gif", ".webp"}
    seen_files = set()

    # Find chart outputs from step results
    for step_id, result in results.items():
        if result.get("status") != "success":
            continue

        for key, value in result.items():
            if isinstance(value, str) and any(value.endswith(ext) for ext in chart_extensions):
                if os.path.exists(value) and value not in seen_files:
                    seen_files.add(value)
                    step_context = next(
                        (s["task"] for s in plan["steps"] if s["id"] == step_id),
                        step_id
                    )
                    audit = audit_chart(value, step_context, pipeline_goal, run_uuid)
                    audits[value] = audit

    # Scan outputs directory for any missed charts
    outputs_dir = Path("outputs")
    if outputs_dir.exists():
        for chart_file in outputs_dir.glob("*"):
            if chart_file.suffix.lower() in chart_extensions:
                filepath = str(chart_file)
                if filepath not in seen_files:
                    seen_files.add(filepath)
                    audit = audit_chart(filepath, "Pipeline output", pipeline_goal, run_uuid)
                    audits[filepath] = audit

    # Overall deployment decision
    if not audits:
        overall = "NO_OUTPUTS"
        deploy = False
        print(f"\n  ⚠️  No visual outputs found to audit")
    else:
        passed = sum(1 for a in audits.values() if a.get("verdict") == "PASS")
        total = len(audits)
        deploy = passed == total
        overall = "PASS" if deploy else "PARTIAL" if passed > 0 else "FAIL"
        print(f"\n  Guardian summary: {passed}/{total} outputs passed")

    report = {
        "overall_verdict": overall,
        "deploy_approved": deploy,
        "audits": audits,
        "total_charts": len(audits),
        "passed": sum(1 for a in audits.values() if a.get("verdict") == "PASS"),
        "pipeline_goal": pipeline_goal,
        "run_uuid": run_uuid
    }

    icon = "✅" if deploy else "❌"
    print(f"  {icon} Deployment decision: {'APPROVED' if deploy else 'BLOCKED'}")

    return report


def print_guardian_report(report: dict):
    """Pretty print the guardian audit report."""
    print(f"\n{'='*50}")
    print(f"GUARDIAN AUDIT REPORT")
    print(f"{'='*50}")
    print(f"Overall verdict: {report['overall_verdict']}")
    print(f"Deploy approved: {report['deploy_approved']}")
    print(f"Charts audited: {report['total_charts']}")
    print(f"Passed: {report['passed']}/{report['total_charts']}")
    if report.get("run_uuid"):
        print(f"Run ID: {report['run_uuid'][:8]}")

    for filepath, audit in report["audits"].items():
        print(f"\n  Chart: {filepath}")
        print(f"  Verdict: {audit.get('verdict')} ({audit.get('confidence', 0):.0%} confidence)")

        findings = audit.get("findings", {})
        for category, observation in findings.items():
            print(f"  {category}: {observation}")

        issues = audit.get("issues", [])
        if issues:
            print(f"  Issues: {', '.join(issues)}")

        metrics = audit.get("metrics_extracted", {})
        if metrics:
            print(f"  Extracted metrics: {json.dumps(metrics, indent=4)}")


if __name__ == "__main__":
    from src.discovery.mcp_server import discover_all_sources
    from src.planner.agent import plan_pipeline, print_plan
    from src.execution.executor import execute_pipeline

    context = discover_all_sources(csv_path="examples/retail.csv")

    goal = "Fetch the top 5 transaction categories by total amount from PostgreSQL and show the results"
    plan = plan_pipeline(goal, context["summary"])
    print_plan(plan)

    results, run_uuid = execute_pipeline(plan, context["summary"])

    report = audit_pipeline_outputs(results, plan, goal, run_uuid)
    print_guardian_report(report)

    # Verify telemetry
    from src.execution.telemetry import get_pipeline_stats
    stats = get_pipeline_stats()
    print(f"\nMLOps Telemetry:")
    print(f"  Total runs: {stats['overall']['total_runs']}")
    print(f"  Total repairs: {stats['overall']['total_repairs']}")
    print(f"  Approved runs: {stats['overall']['approved_runs']}")